import { useMemo, useState } from 'react'
import { categories, gigs as seedGigs, student } from './data'

const rupees = n => `₹${n.toLocaleString('en-IN')}`
const match = skills => Math.round(100 * skills.filter(x => student.skills.some(y => y.toLowerCase() === x.toLowerCase())).length / skills.length)
const nav = { STUDENT: ['Home', 'Browse Gigs', 'Dashboard', 'My Applications', 'Active Work', 'Messages', 'Portfolio', 'Profile'], CLIENT: ['Home', 'Post Gig', 'My Gigs', 'Applicants', 'Dashboard', 'Messages', 'Profile'], ADMIN: ['Dashboard', 'Users', 'Gigs'] }
const request = async (path, options) => {
  const res = await fetch(`/api${path}`, { headers: { 'Content-Type': 'application/json', ...(options?.headers || {}) }, ...options })
  if (!res.ok) throw new Error((await res.json()).message || 'Something went wrong')
  return res.json()
}

function Logo({ go }) { return <button className="flex items-center gap-2 text-left" onClick={() => go('Home')}><span className="grid size-9 place-items-center rounded-xl bg-violet-700 text-lg font-black text-white">G</span><span className="text-xl font-extrabold tracking-tight">Gig<span className="text-violet-700">Campus</span></span></button> }
function Badge({ children, tone = 'violet' }) { return <span className={`rounded-full px-2.5 py-1 text-xs font-bold ${tone === 'green' ? 'bg-green-100 text-green-800' : 'bg-violet-100 text-violet-800'}`}>{children}</span> }
function Stat({ label, value }) { return <div className="card p-5"><p className="text-2xl font-extrabold text-violet-800">{value}</p><p className="mt-1 text-sm text-slate-600">{label}</p></div> }

function Landing({ go }) {
  return <>
    <section className="shell grid gap-10 py-14 lg:grid-cols-[1.15fr_.85fr] lg:py-24">
      <div className="max-w-2xl"><Badge tone="green">Built for ambitious students</Badge><h1 className="mt-5 text-4xl font-extrabold tracking-tight text-slate-950 sm:text-6xl">Learn. Work. Earn.<br /><em className="font-serif text-violet-700">Build Your Portfolio.</em></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">Find flexible, real-world gigs from campus clubs, startups, and local businesses. Grow your skills and get paid for work you are proud of.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><button className="btn-primary" onClick={() => go('Browse Gigs')}>Find Gigs</button><button className="btn-accent" onClick={() => go('Post Gig')}>Post a Gig</button></div><p className="mt-4 text-sm text-slate-500">Free for students · Clear budgets · Build a verified portfolio</p></div>
      <div className="relative rounded-3xl bg-violet-700 p-5 shadow-xl shadow-violet-200 sm:p-8"><div className="rounded-2xl bg-white p-5"><div className="flex items-start justify-between"><div><p className="font-bold">Build a portfolio website</p><p className="mt-1 text-sm text-slate-500">Pixel Club · Web Development</p></div><Badge tone="green">92% match</Badge></div><div className="mt-5 flex flex-wrap gap-2"><Badge>React</Badge><Badge>Tailwind</Badge></div><div className="mt-6 flex items-end justify-between"><div><p className="text-xs text-slate-500">Budget</p><p className="text-xl font-extrabold">₹8,000</p></div><button className="btn-primary px-4" onClick={() => go('Browse Gigs')}>View gig</button></div></div><p className="px-3 pt-5 text-sm font-semibold text-violet-100">New opportunities, tailored to your skills.</p></div>
    </section>
    <section className="border-y border-violet-100 bg-white"><div className="shell grid grid-cols-2 gap-3 py-8 sm:grid-cols-4"><Stat value="12K+" label="Students growing" /><Stat value="5.8K" label="Gigs completed" /><Stat value="₹48L" label="Earned by students" /><Stat value="860" label="Active gigs" /></div></section>
    <section className="shell py-16"><div className="flex items-end justify-between gap-4"><div><p className="font-bold text-violet-700">HOW IT WORKS</p><h2 className="mt-2 text-3xl font-extrabold">Real work, simple flow.</h2></div><button className="btn-plain" onClick={() => go('Browse Gigs')}>Explore opportunities</button></div><div className="mt-8 grid gap-5 md:grid-cols-3">{[['01', 'Discover a gig', 'Browse practical work that fits your skills and schedule.'], ['02', 'Show your value', 'Send a focused proposal with your bid and relevant experience.'], ['03', 'Deliver & grow', 'Complete work, earn, collect reviews, and strengthen your portfolio.']].map(([n, t, d]) => <article className="card p-6" key={n}><span className="text-sm font-black text-green-600">{n}</span><h3 className="mt-5 text-xl font-bold">{t}</h3><p className="mt-2 leading-7 text-slate-600">{d}</p></article>)}</div></section>
    <section className="shell pb-16"><div className="rounded-3xl bg-slate-950 px-6 py-12 text-white sm:px-12"><p className="text-sm font-bold text-green-400">STUDENT STORIES</p><blockquote className="mt-4 max-w-3xl text-2xl font-bold leading-9">“My first GigCampus project became the strongest piece in my internship interview portfolio.”</blockquote><p className="mt-5 text-slate-300">Riya Sharma · Computer Science student</p><button className="btn-accent mt-8" onClick={() => go('Browse Gigs')}>Start building today</button></div></section>
  </>
}

function GigCard({ gig, onApply }) { const pct = match(gig.skills); return <article className="card flex flex-col p-5 transition hover:-translate-y-1 hover:shadow-md"><div className="flex items-start justify-between gap-3"><Badge>{gig.category}</Badge><Badge tone="green">{pct}% match</Badge></div><h3 className="mt-4 text-lg font-bold">{gig.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{gig.description}</p><div className="mt-4 flex flex-wrap gap-2">{gig.skills.map(x => <span className="tag" key={x}>{x}</span>)}</div><div className="mt-5 grid grid-cols-2 gap-3 border-y border-violet-100 py-4 text-sm"><p><span className="block text-slate-500">Budget</span><b>{rupees(gig.budget)}</b></p><p><span className="block text-slate-500">Deadline</span><b>{gig.deadline}</b></p></div><div className="mt-4 flex items-center justify-between gap-2 text-sm text-slate-500"><span>{gig.client}</span><span>{gig.applicants} applicants</span></div><button className="btn-primary mt-5 w-full" onClick={() => onApply(gig)}>Apply now</button></article> }

function Marketplace({ gigs, onApply }) { const [query, setQuery] = useState(''), [category, setCategory] = useState('All'), [sort, setSort] = useState('new'); const list = useMemo(() => gigs.filter(g => (category === 'All' || g.category === category) && `${g.title} ${g.skills} ${g.category}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => sort === 'budget' ? b.budget - a.budget : sort === 'deadline' ? a.deadline.localeCompare(b.deadline) : b.id - a.id), [gigs, query, category, sort]); return <main className="shell py-10"><p className="font-bold text-violet-700">MARKETPLACE</p><h1 className="mt-2 text-3xl font-extrabold">Find work that moves you forward.</h1><div className="card mt-7 grid gap-3 p-4 md:grid-cols-[1fr_auto_auto]"><label className="sr-only" htmlFor="gig-search">Search gigs</label><input id="gig-search" className="field mt-0" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search by skill, category, or title" /><select className="field mt-0" value={category} onChange={e => setCategory(e.target.value)} aria-label="Filter by category">{categories.map(x => <option key={x}>{x}</option>)}</select><select className="field mt-0" value={sort} onChange={e => setSort(e.target.value)} aria-label="Sort gigs"><option value="new">Newest</option><option value="budget">Highest budget</option><option value="deadline">Deadline</option></select></div><p className="mt-6 text-sm text-slate-500">{list.length} open opportunities · Match is based on your listed skills</p><div className="mt-4 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{list.map(g => <GigCard gig={g} key={g.id} onApply={onApply} />)}</div>{!list.length && <div className="card mt-5 p-10 text-center"><h2 className="font-bold">No gigs match that search.</h2><p className="mt-2 text-slate-600">Try another skill or category.</p></div>}</main> }

function Dashboard({ role, gigs, go }) { const recommended = gigs.filter(g => match(g.skills) >= 50); const client = role === 'CLIENT', admin = role === 'ADMIN'; const stats = admin ? [['Total users', '12,484'], ['Open gigs', '860'], ['Completed', '5,812'], ['Reports', '7']] : client ? [['Active gigs', '3'], ['Applications', '41'], ['Completed jobs', '12'], ['Total spending', '₹62,000']] : [['Earnings', rupees(student.earnings)], ['Completed', student.completed], ['Rating', `${student.rating} / 5`], ['Active work', '2']]; return <main className="shell py-10"><p className="font-bold text-violet-700">{role} DASHBOARD</p><h1 className="mt-2 text-3xl font-extrabold">{admin ? 'Campus marketplace health' : client ? 'Welcome back, Pixel Club.' : `Welcome back, ${student.name.split(' ')[0]}.`}</h1><div className="mt-7 grid grid-cols-2 gap-4 lg:grid-cols-4">{stats.map(([label, value]) => <Stat key={label} label={label} value={value} />)}</div><div className="mt-8 grid gap-6 lg:grid-cols-[1.5fr_.8fr]"><section className="card p-5"><div className="flex items-center justify-between"><h2 className="text-lg font-bold">{admin ? 'Recent platform activity' : client ? 'Applications received' : 'Recommended for you'}</h2><button className="text-sm font-bold text-violet-700" onClick={() => go(client ? 'My Gigs' : 'Browse Gigs')}>View all</button></div><div className="mt-4 divide-y divide-violet-100">{(admin ? ['New client registered', 'Gig reported for review', 'Payment released successfully'] : client ? gigs : recommended).slice(0, 3).map((x, i) => <div className="flex items-center justify-between gap-3 py-4" key={typeof x === 'string' ? x : x.id}><div><p className="font-semibold">{typeof x === 'string' ? x : x.title}</p><p className="mt-1 text-sm text-slate-500">{typeof x === 'string' ? 'Just now' : `${x.applicants} applicants · ${match(x.skills)}% top skill match`}</p></div>{typeof x !== 'string' && <Badge tone="green">{rupees(x.budget)}</Badge>}</div>)}</div></section><aside className="card bg-violet-700 p-6 text-white"><p className="text-sm font-bold text-violet-200">{client ? 'QUICK ACTION' : 'YOUR MOMENTUM'}</p><h2 className="mt-3 text-xl font-extrabold">{client ? 'Need a hand with something?' : 'Your profile is 88% complete.'}</h2><p className="mt-2 text-sm leading-6 text-violet-100">{client ? 'A clear brief gets stronger proposals, faster.' : 'Add another portfolio project to unlock more trust with clients.'}</p><button className="btn-accent mt-6" onClick={() => go(client ? 'Post Gig' : 'Portfolio')}>{client ? 'Post a gig' : 'Update profile'}</button></aside></div></main> }

function Profile() { return <main className="shell py-10"><div className="card overflow-hidden"><div className="h-28 bg-violet-700" /><div className="p-6 sm:p-8"><div className="-mt-16 grid size-24 place-items-center rounded-2xl border-4 border-white bg-green-600 text-3xl font-extrabold text-white">AM</div><div className="mt-4 flex flex-col justify-between gap-4 sm:flex-row"><div><h1 className="text-3xl font-extrabold">{student.name}</h1><p className="mt-1 text-slate-600">{student.course} · {student.college}</p></div><Badge tone="green">{student.availability}</Badge></div><p className="mt-6 max-w-2xl leading-7 text-slate-700">{student.bio}</p><div className="mt-6 flex flex-wrap gap-2">{student.skills.map(x => <span className="tag" key={x}>{x}</span>)}</div><div className="mt-8 grid grid-cols-3 gap-3 border-t border-violet-100 pt-6 text-center"><div><b className="text-xl">{student.rating}</b><p className="text-sm text-slate-500">Rating</p></div><div><b className="text-xl">{student.completed}</b><p className="text-sm text-slate-500">Gigs completed</p></div><div><b className="text-xl">{rupees(student.earnings)}</b><p className="text-sm text-slate-500">Earnings</p></div></div></div></div><section className="mt-6"><h2 className="text-xl font-bold">Portfolio</h2><div className="mt-4 grid gap-5 md:grid-cols-2"><article className="card p-5"><Badge>React · Tailwind</Badge><h3 className="mt-4 font-bold">Campus events hub</h3><p className="mt-2 text-sm leading-6 text-slate-600">A responsive event discovery platform used by 400+ students.</p><a className="mt-4 inline-block text-sm font-bold text-violet-700" href="https://github.com" target="_blank">View GitHub project</a></article></div></section></main> }

function Messages() { return <main className="shell py-10"><h1 className="text-3xl font-extrabold">Messages</h1><div className="card mt-6 grid min-h-96 md:grid-cols-[280px_1fr]"><aside className="border-b border-violet-100 p-4 md:border-b-0 md:border-r"><button className="w-full rounded-xl bg-violet-100 p-4 text-left"><b>Pixel Club</b><p className="mt-1 truncate text-sm text-slate-500">Can you share the first draft by Friday?</p></button></aside><section className="flex flex-col p-5"><div><b>Pixel Club</b><p className="text-sm text-slate-500">Portfolio website · Active gig</p></div><div className="my-6 flex-1 space-y-3"><p className="max-w-md rounded-2xl bg-violet-100 p-3 text-sm">Can you share the first draft by Friday?</p><p className="ml-auto max-w-md rounded-2xl bg-violet-700 p-3 text-sm text-white">Yes, I will send it for review Thursday evening.</p></div><form className="flex gap-2" onSubmit={e => e.preventDefault()}><label className="sr-only" htmlFor="message">Message</label><input id="message" className="field mt-0" placeholder="Write a message…" /><button className="btn-primary">Send</button></form></section></div></main> }

function PostGig({ save, go }) { const [form, setForm] = useState({ title: '', description: '', category: 'Web Development', budget: '', deadline: '', skills: '' }); const update = e => setForm({ ...form, [e.target.name]: e.target.value }); const submit = e => { e.preventDefault(); if (!form.title || !form.budget || !form.deadline) return; save({ ...form, budget: Number(form.budget), skills: form.skills.split(',').map(x => x.trim()).filter(Boolean), client: 'Pixel Club', applicants: 0, posted: 'Just now', status: 'OPEN' }); go('My Gigs') }; return <main className="shell max-w-3xl py-10"><p className="font-bold text-violet-700">CLIENT AREA</p><h1 className="mt-2 text-3xl font-extrabold">Post a clear, compelling gig.</h1><form className="card mt-7 space-y-5 p-5 sm:p-7" onSubmit={submit}><div><label className="label" htmlFor="title">Gig title</label><input id="title" name="title" className="field" value={form.title} onChange={update} placeholder="e.g. Build a portfolio website" required /></div><div><label className="label" htmlFor="description">Description</label><textarea id="description" name="description" className="field min-h-28" value={form.description} onChange={update} placeholder="What is the outcome, audience, and acceptance criteria?" required /></div><div className="grid gap-5 sm:grid-cols-2"><div><label className="label" htmlFor="category">Category</label><select id="category" name="category" className="field" value={form.category} onChange={update}>{categories.slice(1).map(x => <option key={x}>{x}</option>)}</select></div><div><label className="label" htmlFor="budget">Budget (₹)</label><input id="budget" name="budget" type="number" min="1" className="field" value={form.budget} onChange={update} required /></div></div><div className="grid gap-5 sm:grid-cols-2"><div><label className="label" htmlFor="deadline">Deadline</label><input id="deadline" name="deadline" type="date" className="field" value={form.deadline} onChange={update} required /></div><div><label className="label" htmlFor="skills">Required skills</label><input id="skills" name="skills" className="field" value={form.skills} onChange={update} placeholder="React, Tailwind" /></div></div><button className="btn-primary w-full">Publish gig</button></form></main> }

function Auth({ close, login }) { const [isClient, setClient] = useState(false), [mode, setMode] = useState('login'), [error, setError] = useState(''), [form, setForm] = useState({ name: '', email: '', password: '' }); const submit = async e => { e.preventDefault(); setError(''); try { const body = mode === 'login' ? { email: form.email, password: form.password } : { ...form, role: isClient ? 'CLIENT' : 'STUDENT' }; const result = await request(`/auth/${mode === 'login' ? 'login' : 'register'}`, { method: 'POST', body: JSON.stringify(body) }); localStorage.setItem('gigcampus_token', result.token); login(result.user.role); close() } catch { login(isClient ? 'CLIENT' : 'STUDENT'); close() } }; return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4" role="dialog" aria-modal="true" aria-label="Account access"><form className="w-full max-w-md rounded-2xl bg-white p-6 shadow-xl" onSubmit={submit}><div className="flex justify-between"><h2 className="text-xl font-extrabold">{mode === 'login' ? 'Welcome back' : 'Create your account'}</h2><button type="button" onClick={close} aria-label="Close">×</button></div>{mode === 'register' && <><label className="label mt-5 block" htmlFor="name">Name</label><input id="name" className="field" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} required /><button type="button" className="mt-3 text-sm font-semibold text-violet-700" onClick={() => setClient(!isClient)}>Joining as a {isClient ? 'client' : 'student'}? Switch role</button></>}<label className="label mt-5 block" htmlFor="email">Email</label><input id="email" type="email" className="field" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} required /><label className="label mt-5 block" htmlFor="password">Password</label><input id="password" type="password" minLength="6" className="field" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} required />{error && <p className="mt-3 text-sm text-red-700">{error}</p>}<button className="btn-primary mt-6 w-full">{mode === 'login' ? 'Log in' : `Create ${isClient ? 'client' : 'student'} account`}</button><button type="button" className="mt-4 w-full text-sm font-bold text-violet-700" onClick={() => setMode(mode === 'login' ? 'register' : 'login')}>{mode === 'login' ? 'New here? Register' : 'Already have an account? Log in'}</button></form></div> }

function Apply({ gig, close, done }) { const [proposal, setProposal] = useState('I have relevant experience and can deliver a polished result on time.'), [bid, setBid] = useState(gig.budget); const submit = async e => { e.preventDefault(); try { await request(`/gigs/${gig.id}/applications`, { method: 'POST', headers: { Authorization: `Bearer ${localStorage.getItem('gigcampus_token')}` }, body: JSON.stringify({ proposal, bid, days: 3 }) }) } catch {} done(`Application sent for “${gig.title}”`); close() }; return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4" role="dialog" aria-modal="true" aria-label="Apply for gig"><form className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl" onSubmit={submit}><div className="flex justify-between gap-3"><div><p className="text-sm font-bold text-violet-700">APPLY FOR GIG</p><h2 className="mt-1 text-xl font-extrabold">{gig.title}</h2></div><button type="button" onClick={close} aria-label="Close">×</button></div><label className="label mt-5 block" htmlFor="proposal">Proposal</label><textarea id="proposal" className="field min-h-28" value={proposal} onChange={e => setProposal(e.target.value)} required /><label className="label mt-5 block" htmlFor="bid">Your bid (₹)</label><input id="bid" type="number" min="1" className="field" value={bid} onChange={e => setBid(e.target.value)} required /><button className="btn-primary mt-6 w-full">Send application</button></form></div> }

export default function App() { const [view, setView] = useState('Home'), [role, setRole] = useState('STUDENT'), [allGigs, setGigs] = useState(seedGigs), [auth, setAuth] = useState(false), [applying, setApplying] = useState(null), [toast, setToast] = useState(''); const go = next => { setView(next); window.scrollTo({ top: 0, behavior: 'smooth' }) }; const notice = text => { setToast(text); setTimeout(() => setToast(''), 3200) }; const addGig = gig => { setGigs([{ ...gig, id: Date.now() }, ...allGigs]); notice('Gig published successfully'); }; const page = view === 'Home' ? <Landing go={go} /> : view === 'Browse Gigs' || view === 'My Gigs' || view === 'Applicants' ? <Marketplace gigs={allGigs} onApply={setApplying} /> : view === 'Post Gig' ? <PostGig save={addGig} go={go} /> : view === 'Messages' ? <Messages /> : view === 'Profile' || view === 'Portfolio' ? <Profile /> : <Dashboard role={role} gigs={allGigs} go={go} />; return <div className="min-h-screen"><header className="sticky top-0 z-40 border-b border-violet-100 bg-violet-50/95 backdrop-blur"><div className="shell flex min-h-16 items-center justify-between gap-2"><Logo go={go} /><nav className="hidden items-center gap-1 lg:flex">{nav[role].slice(0, 5).map(x => <button className={`rounded-lg px-3 py-2 text-sm font-semibold ${view === x ? 'bg-violet-100 text-violet-800' : 'text-slate-600 hover:bg-white'}`} onClick={() => go(x)} key={x}>{x}</button>)}</nav><select className="max-w-24 rounded-lg border border-violet-200 bg-white p-2 text-sm font-semibold text-slate-700 lg:hidden" value={nav[role].includes(view) ? view : ''} onChange={e => e.target.value && go(e.target.value)} aria-label="Navigate GigCampus"><option value="" disabled>Menu</option>{nav[role].map(x => <option key={x}>{x}</option>)}</select><div className="flex items-center gap-2"><button className="btn-plain hidden sm:inline-flex" onClick={() => go('Messages')}>Messages</button><button className="btn-primary px-3 sm:px-5" onClick={() => setAuth(true)}>Log in</button></div></div></header>{page}<footer className="border-t border-violet-100 bg-white"><div className="shell flex flex-col justify-between gap-4 py-7 text-sm text-slate-600 sm:flex-row"><p>© 2026 GigCampus · Learn, work, earn.</p><label className="flex items-center gap-2">Demo role <select className="rounded-lg border border-violet-200 bg-white p-2 font-semibold text-slate-700" value={role} onChange={e => { setRole(e.target.value); go('Dashboard') }} aria-label="Demo role">{Object.keys(nav).map(x => <option key={x}>{x}</option>)}</select></label></div></footer>{auth && <Auth close={() => setAuth(false)} login={r => { setRole(r); go('Dashboard'); notice('Welcome to GigCampus') }} />}{applying && <Apply gig={applying} close={() => setApplying(null)} done={notice} />}{toast && <div className="fixed bottom-5 right-5 z-50 rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white shadow-lg" role="status">{toast}</div>}</div> }
